### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by colbygarland** [colbygarland/teleo-website#2]
- [ ] Add `title` tag
- [ ] Add `description` tag
- [ ] Create favicon
- [x] Compress all images
- [ ] Ensure all scripts/fonts are lazy loaded async
